/** Operational events shown in the M10 demo. Dates are offsets from today. */
export const INCIDENCIAS_DEMO = [
  [
    'INC-2026-0001',
    'SERV/2023/041',
    'FALLO_SERVICIO',
    'GRAVE',
    -21,
    'Ruta norte finalizada con 74 minutos de retraso y tres contenedores pendientes.',
    'CERRADA',
  ],
  [
    'INC-2026-0002',
    'DIP/2024/0117',
    'INCIDENTE_SIN_BAJA',
    'MODERADA',
    -14,
    'Una rama cayó dentro del perímetro de trabajo sin alcanzar al operario ni a terceros.',
    'EN_INVESTIGACION',
  ],
  [
    'INC-2026-0003',
    'CSS/2022/8814',
    'FALLO_SERVICIO',
    'MUY_GRAVE',
    -8,
    'El turno nocturno quedó con dos puestos sin cubrir en el centro de salud principal.',
    'EN_INVESTIGACION',
  ],
  [
    'INC-2026-0004',
    'EMV/2025/0042',
    'QUEJA_USUARIO',
    'MODERADA',
    -5,
    'Una reparación urgente se reprogramó dos veces sin aviso confirmado a la inquilina.',
    'ABIERTA',
  ],
  [
    'INC-2026-0005',
    'SERV/2023/041',
    'VEHICULO',
    'MODERADA',
    -3,
    'Un recolector quedó inmovilizado por avería hidráulica durante el inicio de ruta.',
    'ABIERTA',
  ],
  [
    'INC-2026-0006',
    'CSS/2022/8814',
    'SEGURIDAD_DATOS',
    'GRAVE',
    -2,
    'Un parte con identificadores internos fue enviado a un destinatario externo incorrecto.',
    'EN_INVESTIGACION',
  ],
  [
    'INC-2026-0007',
    'DIP/2024/0117',
    'DANO_MATERIAL',
    'LEVE',
    -1,
    'La desbrozadora proyectó grava y dañó el cristal lateral de un vehículo estacionado.',
    'ABIERTA',
  ],
  [
    'INC-2026-0008',
    'EMV/2025/0042',
    'ACCIDENTE',
    'MODERADA',
    0,
    'Un técnico sufrió una torcedura leve al bajar material por una escalera comunitaria.',
    'ABIERTA',
  ],
] as const;
