export const CONVENIOS_PERSONAL_DEMO = [
  {
    clave: 'viaria',
    nombre: 'Convenio de limpieza pública viaria de la provincia de Sevilla (demo)',
    sector: 'Limpieza viaria y residuos',
    categorias: [
      ['encargado', 'I', 'Encargado de servicio', 3, 1_680],
      ['conductor', 'II', 'Conductor de vehículo especial', 8, 1_445],
      ['operario', 'III', 'Operario de recogida', 10, 1_285],
    ],
  },
  {
    clave: 'jardineria',
    nombre: 'Convenio de jardinería de Andalucía (demo)',
    sector: 'Jardinería',
    categorias: [
      ['encargado', 'I', 'Encargado jardinero', 3, 1_630],
      ['jardinero', 'II', 'Oficial jardinero', 8, 1_410],
      ['peon', 'III', 'Peón de jardinería', 10, 1_260],
    ],
  },
  {
    clave: 'limpieza',
    nombre: 'Convenio de limpieza de edificios y locales de Sevilla (demo)',
    sector: 'Limpieza de edificios',
    categorias: [
      ['supervisor', 'I', 'Supervisor de centro', 3, 1_575],
      ['limpiador', 'II', 'Especialista de limpieza', 10, 1_250],
    ],
  },
  {
    clave: 'construccion',
    nombre: 'Convenio de construcción y obras públicas de Sevilla (demo)',
    sector: 'Mantenimiento y obras',
    categorias: [
      ['encargado', 'I', 'Encargado de mantenimiento', 3, 1_790],
      ['oficial', 'II', 'Oficial de primera', 8, 1_565],
      ['peon', 'III', 'Peón especialista', 10, 1_335],
    ],
  },
  {
    clave: 'deportivo',
    nombre: 'Convenio estatal de instalaciones deportivas (demo)',
    sector: 'Instalaciones deportivas',
    categorias: [
      ['coordinador', 'I', 'Coordinador de instalación', 3, 1_610],
      ['auxiliar', 'II', 'Auxiliar de control de accesos', 10, 1_265],
    ],
  },
] as const;

export const EQUIPOS_PERSONAL_DEMO = [
  [
    'SERV/2023/041',
    'viaria',
    'Base operativa norte',
    [
      ['encargado', 1, 1],
      ['conductor', 5, 5],
      ['operario', 8, 9],
    ],
  ],
  [
    'DIP/2024/0117',
    'jardineria',
    'Centros provinciales',
    [
      ['encargado', 1, 1],
      ['jardinero', 3, 3],
      ['peon', 4, 4],
    ],
  ],
  [
    'CSS/2022/8814',
    'limpieza',
    'Centro de salud principal',
    [
      ['supervisor', 1, 1],
      ['limpiador', 11, 12],
    ],
  ],
  [
    'EMV/2025/0042',
    'construccion',
    'Taller de reparaciones',
    [
      ['encargado', 1, 1],
      ['oficial', 4, 4],
      ['peon', 2, 2],
    ],
  ],
  [
    'SERV/2026/007',
    'deportivo',
    'Complejo deportivo municipal',
    [
      ['coordinador', 1, 1],
      ['auxiliar', 4, 6],
    ],
  ],
] as const;

export const NOMBRES_PERSONAL_DEMO = [
  'Alba',
  'Alejandro',
  'Ana',
  'Antonio',
  'Beatriz',
  'Carlos',
  'Carmen',
  'Daniel',
  'David',
  'Elena',
  'Fernando',
  'Francisco',
  'Inés',
  'Isabel',
  'Javier',
  'José',
  'Laura',
  'Lucía',
  'Manuel',
  'María',
  'Marta',
  'Miguel',
  'Nuria',
  'Pablo',
  'Patricia',
  'Raúl',
  'Rocío',
  'Rubén',
  'Sara',
  'Sergio',
  'Silvia',
  'Sonia',
  'Teresa',
  'Víctor',
  'Adrián',
  'Ángela',
  'Cristina',
  'Diego',
  'Eva',
  'Felipe',
  'Gloria',
  'Hugo',
  'Irene',
  'Jaime',
  'Lidia',
  'Marcos',
] as const;

export const APELLIDOS_PERSONAL_DEMO = [
  'Aguilar Moreno',
  'Benítez Ruiz',
  'Cabrera León',
  'Domínguez Vega',
  'Escudero Gil',
  'Fernández Mora',
  'García Ponce',
  'Herrera Cano',
  'Iglesias Rey',
  'Jiménez Soto',
  'López Vidal',
  'Martín Rojas',
  'Navarro Sáez',
  'Ortega Cruz',
  'Pérez Núñez',
  'Ramírez Soler',
] as const;
